#ifndef __CONSTANTS_H__
#define DEFAULT_CNF_PORT 8080
#define DEFAULT_CNF_ADDR "127.0.0.1"
#define BACKLOG 100
#define MAX_MASTER_SHARDS 100
#define MAX_FLWR_PER_MASTER 2
#define MAX_THREADS 10
#define HEARTBEAT_INTERVAL 2
#define HEARTBEAT_INTERVAL_WITH_SLACK 5
#define SHARD_MAITNENANCE_INTERVAL 5
#endif // !__CONSTANTS_H__
